### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jhdulaney** [jeffbuttars/cowpy#4]
Just out of curiosity, what license is this?  I'm looking to package in Fedora and possibly Centos.  It would need to be an FSF approved license.

**Comment by jeffbuttars** [comment]
No license currently. I'll add one.

I'll use Apache 2.0 unless that's problematic for packaging.

http://directory.fsf.org/wiki/License:Apache2.0

**Comment by jhdulaney** [comment]
Nope, that quite works.
